AllCops:
    Include:
        - bin/docme
        - lib/**/*
    Exclude:
        - test/**/*
        - coverage/**/*
        - docme_site/**/*
        - Rakefile
        - Gemfile
        - docme.gemspec
        - lib/templates/**/*

Documentation:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

IndentationWidth:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

CyclomaticComplexity:
  Max: 12

Style/Next:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: false

# Style/ClassLength:
#   Max: 134