AllCops:
    Include:
        - bin/docme
        - lib/**/*
    Exclude:
        - test/**/*
        - coverage/**/*
        - docme_site/**/*
        - Rakefile
        - Gemfile
        - docme.gemspec
        - lib/templates/**/*

Documentation:
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

EmptyLinesAroundMethodBody:
  Enabled: false

IndentationWidth:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

AbcSize:
  Max: 48

CyclomaticComplexity:
  Max: 14

PerceivedComplexity:
  Max: 15

Style/Next:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: false